사용자 조회 API에 Tokens 필드 추가
JAVACAFE-STUDY/chainity-api pull request #26
Opened 2019-06-07 09:03 UTC by kioku714

#12

2019-06-07 14:23 UTC, rygh4775 requested changes
~~keystore가 아직 등록되지 않은 유저의 경우 address가 존재하지 않아 에러가 발생할 것 같습니다.
추가적으로 `_id`, `email`, `status`, `role`, `createdAt` 을 제외한 모든 필드는 존재 하지 않을 수도 있습니다.~~
코드에 작성 이동

2019-06-07 14:24 UTC, rygh4775 requested changes

2019-06-07 14:24 UTC, rygh4775 commented on controllers/user.controller.js
> +  const tokenOwner = req.user.keyStore.address;
keystore가 아직 등록되지 않은 유저의 경우 address가 존재하지 않아 에러가 발생할 것 같습니다.

2019-06-07 14:24 UTC, rygh4775 commented on controllers/user.controller.js
> +    var user = {
_id, email, status, role, createdAt 을 제외한 모든 필드는 존재 하지 않을 수도 있습니다.

2019-06-07 15:20 UTC, kioku714 commented on controllers/user.controller.js
> +  const tokenOwner = req.user.keyStore.address;
@rygh4775 회원가입과 동시에 keystore가 생성되지 않나요?

2019-06-07 15:24 UTC, rygh4775 commented on controllers/user.controller.js
> +  const tokenOwner = req.user.keyStore.address;
회원가입 전에 초대 상태가 있어요.

2019-06-08 02:25 UTC, rygh4775 requested changes

2019-06-08 02:25 UTC, rygh4775 commented on controllers/user.controller.js
> +  const user = {
기존 user정보에 tokens만 추가되는 게 가장 좋은 방법일 것 같긴 한데요.

예상되는 side effect
- user 필드 추가시 누락
- 클라이언트 측에서 공백에 대한 처리 필요
  @kyungseop 존재하지 않는 필드를 공백으로 내려줄 경우 처리가 되어있을까요?

2019-06-08 03:19 UTC, kioku714 commented on controllers/user.controller.js
> +  const user = {
user 정보에 token 필드만 추가하려하였으나 "req.user.token = (토큰값)" 방식으로는 필드 추가가 안되더라구요. 필드가 없을 경우를 문자열 공백처리가 필요하다는 것으로 제가 현수씨 코멘트를 잘못 이해한 것 같은데, 첫번째 코드(공백 문자열 처리 전)에서 필드 없을 경우에 아래와 같은 결과값으로 반환됩니다. 
```
{
_id: "5ccecc8ade0d1039d229252a",
email: "system",
name: "system",
status: "active",
role: "system",
createdAt: "2019-05-05T11:44:10.203Z",
keyStore: {},
tokens: "9999973178"
}
```

2019-06-08 09:34 UTC, rygh4775 commented on controllers/user.controller.js
> +  const user = {
네 그렇긴 한데,
보여주신 결과는 샘플이겠죠? keyStore가 빈 값을 가지고 있을 수는 없어서
### 초대  받은 상태의 user 조회 결과
```
{
            "__v": 0,
            "_id": "5cda332f0446ffe92e151d27",
            "createdAt": "2019-05-14T03:17:03.538Z",
            "email": "rygh4775@nate.com",
            "id": "5cda332f0446ffe92e151d27",
            "role": "user",
            "status": "invited"
}
```

2019-06-08 11:53 UTC, kioku714 commented on controllers/user.controller.js
> +  const user = {
@rygh4775 아래 데이터를 복붙하니까 keystore가 빈값처럼 복사되네요
<img width="346" alt="스크린샷 2019-06-08 오후 8 51 26" src="https://user-images.githubusercontent.com/5554936/59146920-4c514000-8a2f-11e9-8515-b768552f9e47.png">

2019-06-08 11:56 UTC, closed without merging