[Critical] 프로필 사진 업데이트시 로그인 실패 #297
JAVACAFE-STUDY/chainity-api pull request #54
Opened 2019-08-18 06:00 UTC by clghks

- 업데이트 관련 수정

2019-08-18 06:19 UTC, rygh4775 requested changes

2019-08-18 06:19 UTC, rygh4775 commented on controllers/user.controller.js
> +      "$set": {
https://github.com/JAVACAFE-STUDY/chainity-api/blob/develop/routes/auth.route.js
https://github.com/JAVACAFE-STUDY/chainity-api/blob/develop/controllers/auth.controller.js
@clghks 위 두 코드를 보시면 유저 업데이트시 사용하는 필드가 있는데 수정한 코드에는 해당 필드들이 빠져있네요.

2019-08-18 06:21 UTC, rygh4775 commented on controllers/user.controller.js
> +      "$set": {
그리고 해당 이슈가 왜 발생되었는지 간단히라도 공유해주시면 좋을 것 같아요

2019-08-18 15:36 UTC, clghks commented on controllers/user.controller.js
> +      "$set": {
@rygh4775  유저 업데이트에서 사용하는 필드 추가 했습니다.

2019-08-18 15:49 UTC, clghks commented on controllers/user.controller.js
> +      "$set": {
@rygh4775 이번 이슈는 User 정보를 업데이트 할때 keyStore가 없어서 발생하였습니다. 
히스토리를 확인해보니 User 조회 시 keyStore를 빼는 옵션이 추가 되어 있어서 관련 예외처리를 추가 하였습니다. 

https://github.com/JAVACAFE-STUDY/chainity-api/commit/431f5f3239c8efbe25b220fc3d54113c2974f723

2019-08-19 00:07 UTC, rygh4775 requested changes

2019-08-19 00:07 UTC, rygh4775 commented on controllers/user.controller.js
> -  const user = new User(req.user);
https://github.com/JAVACAFE-STUDY/chainity-api/blob/3f85a57d2f540da982ea744d4021840764a5f52e/controllers/auth.controller.js#L70
위 코드를 보면 업데이트할 항목을 req.user에 담아서 보내고 있어 정상적으로 처리 안될 것 같습니다.

2019-08-19 00:07 UTC, rygh4775 commented on controllers/user.controller.js
> +  if (req.body.registeredAt) {
이 부분은 위와 같은 이유로 실질적으로 조건을 만족하는 케이스는 없을 것 같아요.

2019-08-19 00:07 UTC, rygh4775 commented on controllers/user.controller.js
> +  if (req.body.keyStore) {
이 부분은 위와 같은 이유로 실질적으로 조건을 만족하는 케이스는 없을 것 같아요.

2019-08-19 00:07 UTC, rygh4775 commented on controllers/user.controller.js
> +      "$set": user
$set을 이용하면 업데이트 필드를 명확히 파악 가능하여 좋을 것 같네요

2019-08-20 15:54 UTC, clghks commented on controllers/user.controller.js
> -  const user = new User(req.user);
@rygh4775 사용자 등록부분 수정했습니다.

2019-08-25 01:42 UTC, rygh4775 approved these changes

2019-08-29 15:50 UTC, merged